name: 刷步数

on:
  workflow_dispatch:
    inputs:
      user:
        description: 'user'
        required: true
        default: ''
      pwd:
        description: 'pwd'
        required: true
        default: ''
      step:
        description: 'step'
        required: false
        default: '0'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: 开始
      run: |
        echo "Hello ${{ github.event.inputs.user }}!"
        echo "- in ${{ github.event.inputs.pwd }}!"
        echo "- step ${{ github.event.inputs.step }}!"
        pip install requests
        user='${{ github.event.inputs.user }}'
        pwd='${{ github.event.inputs.pwd }}'
        step='${{ github.event.inputs.step }}'
        
        python3 main.py <<EOF
        ${user}
        ${pwd}
        ${step}
        EOF
